### ISSUE TITLE
[Workaround] linebreaks cut off additional webhook messages.

### ISSUE THREAD

**Issue by LucesEnBabel** [kalynrobinson/discord_integration#4]
Inserting a linebreak in "Additional Webhooks" deletes the rest of the message.

A workaround I used is to use "\n" as a linebreak.

```**{$mybb->input["subject"]}**\n$messageshort\n\nYou can see the complete announcement in $threadurl```
![clipboard02](https://cloud.githubusercontent.com/assets/25283175/25856960/f77f180a-34ad-11e7-936f-8a7a69a9eaf5.png)

**Comment by kalynrobinson** [comment]
Yeah, this is due to the way I'm splitting up that entire settings block—that is, splitting on newlines. I'll likely modify the Additional Webhooks format to something like

```
-webhook=<webhook>
-message=This is the first line of the first message.

This is the second line of the first message.

---

-webhook=<webhook>
-message=This is the first line of the second message.

This is the second line of the second message.
```

Note the hyphens in front of each setting field, e.g. `-webhook`. I want to avoid using regex to process the settings, so this is the best way I can think to.

**Comment by kalynrobinson** [comment]
The aforementioned change has been made.

Please adjust your settings so that each attribute is prefixed with a hyphen, as presented above.

**Comment by kalynrobinson** [comment]
@LucesEnBabel closing this issue for now. Looking into cleaner/better alternatives.
